---
image: "ghcr.io/mullholland/docker-molecule-shell:latest"

services:
  - docker:dind

stages:
  - linting
  - "default-previous"
  - "default-current"
  - "default-development"
  - "version-lock-previous"
  - "version-lock-current"
  - "version-lock-development"

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

linting:
  stage: linting
  variables:
    COMMAND: "lint"
  script:
    - "command=${COMMAND} /opt/molecule.sh"


"default-previous":
  needs:
    - "linting"
  stage: "default-previous"
  variables:
    SCENARIO: "default"
    ANSIBLE: "previous"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian10, debian11, ubuntu1804, ubuntu2004, ubuntu2204]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"default-current":
  needs:
    - "linting"
  stage: "default-current"
  variables:
    SCENARIO: "default"
    ANSIBLE: "current"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian10, debian11, ubuntu1804, ubuntu2004, ubuntu2204]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"default-development":
  needs:
    - "linting"
  allow_failure: true
  stage: "default-development"
  variables:
    SCENARIO: "default"
    ANSIBLE: "development"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian10, debian11, ubuntu1804, ubuntu2004, ubuntu2204]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"version-lock-previous":
  needs:
    - "linting"
  stage: "version-lock-previous"
  variables:
    SCENARIO: "version-lock"
    ANSIBLE: "previous"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian10, debian11, ubuntu1804, ubuntu2004, ubuntu2204]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"version-lock-current":
  needs:
    - "linting"
  stage: "version-lock-current"
  variables:
    SCENARIO: "version-lock"
    ANSIBLE: "current"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian10, debian11, ubuntu1804, ubuntu2004, ubuntu2204]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"version-lock-development":
  needs:
    - "linting"
  allow_failure: true
  stage: "version-lock-development"
  variables:
    SCENARIO: "version-lock"
    ANSIBLE: "development"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian10, debian11, ubuntu1804, ubuntu2004, ubuntu2204]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"
