---
- name: YUM | Add mongodb repository
  ansible.builtin.yum_repository:
    name: "{{ mongodb_yum_repository.name }}"
    description: "{{ mongodb_yum_repository.name }}"
    file: "{{ mongodb_yum_repository.name }}"
    baseurl: "{{ mongodb_yum_repository.baseurl }}"
    gpgcheck: "{{ mongodb_yum_repository.gpgcheck }}"
    gpgkey: "{{ mongodb_yum_repository.gpgkey }}"
    enabled: "{{ mongodb_yum_repository.enabled }}"

- name: yum | Install mongodb
  ansible.builtin.yum:
    name: "{{ mongodb_packages }}"
    state: present

- name: YUM |  Install yum-plugin-versionlock
  ansible.builtin.yum:
    name: "yum-plugin-versionlock"
    update_cache: true
    state: present
  when: mongodb_packages_pin

- name: YUM | yum-plugin-versionlock mongodb_packages
  ansible.builtin.command: yum versionlock {{ item }}
  with_items:
    - "{{ mongodb_packages }}"
  when: mongodb_packages_pin
  # YUM module does not support versionlock ATM
  tags:
    - skip_ansible_lint
    - molecule-idempotence-notest
