---
molecule_exceptions:
  - variation: "RedHat/CentOS/Fedora"
    reason: "Not fully tested because of weird behaviour while testing with molecule/Docker."
  - variation: "Rockylinux"
    reason: "Not fully tested because of weird behaviour while testing with molecule/Docker."
  - variation: "Almalinux"
    reason: "Not fully tested because of weird behaviour while testing with molecule/Docker."
  - variation: "Amazonlinux"
    reason: "Not officially supported."
  - variation: "Ubuntu 2204"
    reason: "No release file ATM."
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current"]
    platforms:
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"

  - scenario: "version-lock"
    ansible: ["previous", "current"]
    platforms:
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
