---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Check mongodb is installed
      ansible.builtin.package:
        name: "mongodb-org"
        state: present
      register: check_mongodb_package
      failed_when: (check_mongodb_package is changed) or (check_mongodb_package is failed)

    - name: check mongod daemon
      service:
        name: "mongod"
        state: started
        enabled: true
      check_mode: true
      register: check_mongodb_service
      failed_when: (check_mongodb_service is changed) or (check_mongodb_service is failed)


    - name: check mongod config
      lineinfile:
        name: "/etc/mongod.conf"
        line: "# Ansible managed: Do NOT edit this file manually!"
        state: present
        owner: "root"
        group: "root"
        mode: "0644"
      check_mode: true
      register: check_mongodb_config
      failed_when: (check_mongodb_config is changed) or (check_mongodb_config is failed)
